package com.wcdk.r2dbc.repository;

import com.wcdk.r2dbc.R2dbcRepositoryOperations;
import com.wcdk.r2dbc.R2dbcUtil;
import com.wcdk.r2dbc.config.WcdkR2dbcProperties;
import com.wcdk.r2dbc.dialect.DatabaseDialects;
import com.wcdk.r2dbc.query.QueryWrapper;
import com.wcdk.r2dbc.query.xml.RepositoryXmlRegistry;
import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.ConnectionFactoryOptions;
import io.r2dbc.spi.ConnectionFactoryProvider;
import java.util.ServiceLoader;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.data.annotation.Id;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.relational.core.mapping.Table;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.r2dbc.connection.R2dbcTransactionManager;
import org.springframework.transaction.reactive.TransactionalOperator;
import reactor.core.publisher.Mono;

import java.time.Duration;

import static org.assertj.core.api.Assertions.assertThat;

/*** 各真实数据库共享的行为验收；仅清理本次成功创建的专属表。 @author wcdk ***/
final class DatabaseMatrixSupport {
    static final Duration TIMEOUT = Duration.ofSeconds(45);

    /** DM 1.0.0 throws on foreign driver names in supports(); select the declared provider first. */
    static ConnectionFactory connectionFactory(ConnectionFactoryOptions options) {
        String driver = (String) options.getRequiredValue(ConnectionFactoryOptions.DRIVER);
        for (ConnectionFactoryProvider provider : ServiceLoader.load(ConnectionFactoryProvider.class)) {
            if (driver.equals(provider.getDriver()) && provider.supports(options)) {
                return provider.create(options);
            }
        }
        throw new IllegalStateException("No matching matrix driver: " + driver);
    }

    static MatrixRepository repository(ConnectionFactory factory) {
        return repository(factory, true);
    }

    private static MatrixRepository repository(ConnectionFactory factory, boolean quoted) {
        var properties = new WcdkR2dbcProperties();
        properties.setSnowflakeId(false);
        properties.setQuoteIdentifier(quoted);
        properties.setSqlLogEnabled(false);
        var util = new R2dbcUtil(DatabaseClient.create(factory), null, null, properties);
        var registry = new RepositoryXmlRegistry(new PathMatchingResourcePatternResolver(), properties);
        return (MatrixRepository) new RepositoryProxyFactory(new R2dbcRepositoryOperations(util), properties, registry)
                .create(MatrixRepository.class);
    }

    static void verify(ConnectionFactory factory) {
        verify(factory, true);
        verify(factory, false);
    }

    private static void verify(ConnectionFactory factory, boolean quoted) {
        var dialect = DatabaseDialects.get(factory);
        var client = DatabaseClient.create(factory);
        String table = quoted ? dialect.quoteIdentifier("wcdk_matrix_qa") : "wcdk_matrix_qa";
        String id = quoted ? dialect.quoteIdentifier("id") : "id";
        String name = quoted ? dialect.quoteIdentifier("name") : "name";
        String deleted = quoted ? dialect.quoteIdentifier("del_flg") : "del_flg";
        String identity = switch (dialect.databaseType()) {
            case MYSQL -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case POSTGRESQL -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case ORACLE -> "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case DM -> "BIGINT IDENTITY(1,1) PRIMARY KEY";
            default -> throw new IllegalStateException("Unsupported matrix dialect");
        };
        client.sql("CREATE TABLE " + table + " (" + id + " " + identity + ", " + name
                + " VARCHAR(64) DEFAULT 'default', " + deleted + " INTEGER DEFAULT 0)")
                .fetch().rowsUpdated().then().block(TIMEOUT);
        try {
            var repository = repository(factory, quoted);
            assertThat(repository.exists(new QueryWrapper<>()).block(TIMEOUT)).isFalse();
            assertThat(repository.existsByName("default").block(TIMEOUT)).isFalse();

            // All business fields are null: exercise the dialect's empty INSERT and generated-key path.
            var defaults = repository.insert(new MatrixRow()).block(TIMEOUT);
            assertThat(defaults).isNotNull();
            assertThat(defaults.id).isPositive();
            var stored = repository.selectById(defaults.id).block(TIMEOUT);
            assertThat(stored.name).isEqualTo("default");
            assertThat(stored.delFlg).isZero();
            assertThat(repository.existsByName("default").block(TIMEOUT)).isTrue();
            assertThat(repository.exists(new QueryWrapper<MatrixRow>().eq("name", "default")).block(TIMEOUT)).isTrue();

            var next = new MatrixRow();
            next.name = "second";
            repository.insert(next).block(TIMEOUT);
            assertThat(next.id).isGreaterThan(defaults.id);
            var page = repository.selectPage(PageRequest.of(0, 1, Sort.by(Sort.Order.desc("id"))))
                    .block(TIMEOUT);
            assertThat(page.getTotalElements()).isEqualTo(2);
            assertThat(page.getContent()).extracting(row -> row.id).containsExactly(next.id);
            assertThat(repository.selectPage(PageRequest.of(1, 1, Sort.by("id"))).block(TIMEOUT).getContent())
                    .extracting(row -> row.id).containsExactly(next.id);

            assertThat(repository.deleteById(defaults.id).block(TIMEOUT)).isEqualTo(1);
            assertThat(repository.existsByName("default").block(TIMEOUT)).isFalse();
            assertThat(repository.exists(new QueryWrapper<MatrixRow>().eq("name", "default")).block(TIMEOUT)).isFalse();
            assertThat(repository.exists(new QueryWrapper<MatrixRow>().eq("delFlg", 1)).block(TIMEOUT)).isTrue();
            var transaction = TransactionalOperator.create(new R2dbcTransactionManager(factory));
            var rolledBack = new MatrixRow();
            rolledBack.name = "rollback";
            try {
                transaction.transactional(repository.insert(rolledBack)
                        .then(Mono.error(new IllegalStateException("rollback marker")))).block(TIMEOUT);
                throw new AssertionError("Rollback expected");
            } catch (IllegalStateException expected) {
                assertThat(expected).hasMessageContaining("rollback marker");
            }
            assertThat(repository.existsByName("rollback").block(TIMEOUT)).isFalse();

            // Direct numeric contract: SQL returns 1/0, never a database-specific boolean.
            String query = dialect.pagination("SELECT 1 FROM " + table + " WHERE " + name + " = 'second'", 0, 1);
            assertThat(client.sql(dialect.existsResult(query)).map((row, metadata) -> ((Number) row.get(0)).intValue())
                    .one().block(TIMEOUT)).isEqualTo(1);
            String absent = dialect.pagination("SELECT 1 FROM " + table + " WHERE " + name + " = 'absent'", 0, 1);
            assertThat(client.sql(dialect.existsResult(absent)).map((row, metadata) -> ((Number) row.get(0)).intValue())
                    .one().block(TIMEOUT)).isZero();
        } finally {
            client.sql("DROP TABLE " + table).fetch().rowsUpdated().then().block(TIMEOUT);
        }
    }

    interface MatrixRepository extends BaseRepository<MatrixRow> {
        Mono<Boolean> existsByName(String name);
    }

    @Table("wcdk_matrix_qa")
    static class MatrixRow {
        @Id Long id;
        String name;
        Integer delFlg;
    }
}
